# Site settings
title: Halidu Abdulai
subtitle: Doctoral Researcher in AI in Healthcare
name: Halidu Abdulai
email: halidu.abdulai@abo.fi 
description: >- 
  Personal academic website of Halidu Abdulai, a doctoral researcher at Åbo Akademi University, 
  focusing on the application of Artificial Intelligence in Healthcare.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://abdulaihalidu.github.io"
# Social Profiles
twitter_username: 
github_username: 
linkedin_username: halidu-abdulai
scholar:
  id: 

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Defaults for posts, pages, etc.
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      
# Author information
author:
  name: "Halidu Abdulai"
  avatar: "/assets/images/bio-photo.jpg" 
  bio: "Doctoral Researcher at Åbo Akademi University. <br> AI-based analysis of multi-modal data for diagnosing neurodegenerative diseases."
  location: "Turku, Finland"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:halidu.abdulai@abo.fi" 
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/halidu-abdulai/"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-8687-3413"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: 

# Site Navigation
masthead:
  nav:
    - title: "About"
      url: /about/
    - title: "Research"
      url: /portfolio/
    - title: "Publications"
      url: /publications/
    - title: "CV"
      url: /cv/

# Search
search: true

# Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/halidu-abdulai/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/abdulaihalidu" 
